### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NyxKazuya** [xemulat/Cassini#1]
the bot connects but there is no reason for the category to be able to execute commands

**Comment by xemulat** [comment]
what

**Comment by NyxKazuya** [comment]
> 

guild_id?

**Comment by xemulat** [comment]
> no reason for the category to be able to execute commands

The RAT is meant to be compiled into an exe file and send to the victim.

**Comment by NyxKazuya** [comment]
> > no reason for the category to be able to execute commands
> 
> The RAT is meant to be compiled into an exe file and send to the victim.

does not connect to the channel id, the bot looks active but the commands do not work

**Comment by xemulat** [comment]
hmmm

**Comment by xemulat** [comment]
i'll upload a fix asap
